version: "3"

services:
  loki:
          #    network_mode: host
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    volumes:
      - /etc/docker/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - /var/log:/var/log
      - /etc/docker/promtail-config.yaml:/etc/promtail/promtail-config.yaml

    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
          #    network_mode: host
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
